import "server-only";

import { createServiceRoleClient } from "@/lib/supabase/service-role";
import { isAutoGeneratedMaLop } from "@/lib/to-chuc/khoa-hoc-labels";
import type { LoaiMoHinhKhoa, HinhThucLop, TrangThaiLop } from "@/lib/to-chuc/khoa-hoc-types";
import type { LopHocQuanLyRow } from "@/lib/to-chuc/lop-hoc-quan-ly-types";

export type { LopHocQuanLyRow } from "@/lib/to-chuc/lop-hoc-quan-ly-types";

/** Danh sách lớp toàn org — trang quản lý Khóa & lớp. */
export async function listLopHocQuanLy(
  orgId: string,
): Promise<LopHocQuanLyRow[]> {
  const admin = createServiceRoleClient();
  const { data: khoaRows } = await admin
    .from("org_khoa_hoc")
    .select("id, slug, ten_khoa_hoc, loai_mo_hinh")
    .eq("id_to_chuc", orgId)
    .order("ten_khoa_hoc", { ascending: true });

  const khoaList = khoaRows ?? [];
  if (khoaList.length === 0) return [];

  const khoaById = new Map(
    khoaList.map((k) => [
      k.id as string,
      {
        slug: k.slug as string,
        ten: k.ten_khoa_hoc as string,
        loaiMoHinh: k.loai_mo_hinh as LoaiMoHinhKhoa,
      },
    ]),
  );
  const khoaIds = [...khoaById.keys()];

  const { data: lopRows, error } = await admin
    .from("org_lop_hoc")
    .select(
      "id, ma_lop, hinh_thuc, lich_hoc, ngay_khai_giang, slot_toi_da, trang_thai, giao_vien_phu_trach, giao_vien_text, id_khoa_hoc",
    )
    .in("id_khoa_hoc", khoaIds)
    .order("ngay_khai_giang", { ascending: false });

  if (error) throw new Error(error.message);

  const list = lopRows ?? [];
  if (list.length === 0) return [];

  const lopIds = list.map((l) => l.id as string);
  const gvIds = [
    ...new Set(
      list
        .map((l) => l.giao_vien_phu_trach as string | null)
        .filter((id): id is string => Boolean(id)),
    ),
  ];

  const [hvRes, gvRes] = await Promise.all([
    admin
      .from("user_hoc_vien_lop")
      .select("id_lop_hoc")
      .in("id_lop_hoc", lopIds)
      .in("trang_thai", ["da_dang_ky", "dang_hoc"]),
    gvIds.length
      ? admin
          .from("user_nguoi_dung")
          .select("id, ten_hien_thi")
          .in("id", gvIds)
      : Promise.resolve({ data: [] as Array<Record<string, unknown>> }),
  ]);

  const hvCount = new Map<string, number>();
  for (const row of hvRes.data ?? []) {
    const lopId = row.id_lop_hoc as string | null;
    if (!lopId) continue;
    hvCount.set(lopId, (hvCount.get(lopId) ?? 0) + 1);
  }

  const gvTenById = new Map(
    (gvRes.data ?? []).map((u) => [
      u.id as string,
      (u.ten_hien_thi as string) || "Giảng viên",
    ]),
  );

  return list.map((row) => {
    const khoa = khoaById.get(row.id_khoa_hoc as string);
    const maRaw = (row.ma_lop as string | null)?.trim() ?? "";
    const maLop =
      maRaw && !isAutoGeneratedMaLop(maRaw) ? maRaw : null;
    const gvId = (row.giao_vien_phu_trach as string | null) ?? null;
    const gvText = (row.giao_vien_text as string | null)?.trim() || null;

    return {
      id: row.id as string,
      maLop,
      lichHoc: (row.lich_hoc as string | null) ?? null,
      hinhThuc: row.hinh_thuc as HinhThucLop,
      ngayKhaiGiang: row.ngay_khai_giang as string,
      slotToiDa: (row.slot_toi_da as number | null) ?? null,
      trangThaiLop: row.trang_thai as TrangThaiLop,
      giaoVienPhuTrach: gvId,
      giaoVienText: gvText,
      giaoVienTen: gvId
        ? (gvTenById.get(gvId) ?? "Giảng viên")
        : gvText,
      khoaId: row.id_khoa_hoc as string,
      khoaSlug: khoa?.slug ?? "",
      tenKhoa: khoa?.ten ?? "Khóa",
      loaiMoHinh: khoa?.loaiMoHinh ?? "lien_tuc_theo_thang",
      soHocVien: hvCount.get(row.id as string) ?? 0,
    };
  });
}
