#!/usr/bin/env bash
# Chuẩn hoá tên secret GitHub Actions → biến env deploy (OpenNext + Wrangler).
set -euo pipefail

pick() {
  for candidate in "$@"; do
    if [ -n "${!candidate:-}" ]; then
      printf '%s' "${!candidate}"
      return 0
    fi
  done
  return 1
}

export CLOUDFLARE_API_TOKEN="$(pick CLOUDFLARE_API_TOKEN || true)"
export CLOUDFLARE_ACCOUNT_ID="$(pick CLOUDFLARE_ACCOUNT_ID || true)"
export DATABASE_URL="$(pick DATABASE_URL || true)"
export CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE="$(
  pick CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE DATABASE_URL || true
)"
# Wrangler / OpenNext gần đây cũng đọc prefix WRANGLER_…
export WRANGLER_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE="${
  WRANGLER_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE:-$CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE
}"
export NEXT_PUBLIC_SITE_URL="${NEXT_PUBLIC_SITE_URL:-https://cins.vn}"
export NEXT_PUBLIC_SUPABASE_URL="$(pick NEXT_PUBLIC_SUPABASE_URL || true)"
export NEXT_PUBLIC_SUPABASE_ANON_KEY="$(pick NEXT_PUBLIC_SUPABASE_ANON_KEY || true)"
export NEXT_PUBLIC_CF_IMAGES_ACCOUNT_HASH="$(pick NEXT_PUBLIC_CF_IMAGES_ACCOUNT_HASH || true)"
export NEXT_PUBLIC_BUNNY_LIBRARY_ID="$(
  pick NEXT_PUBLIC_BUNNY_LIBRARY_ID BUNNY_LIBRARY_ID || true
)"
export NEXT_PUBLIC_BUNNY_CDN_HOSTNAME="$(
  pick NEXT_PUBLIC_BUNNY_CDN_HOSTNAME BUNNY_CDN_HOSTNAME BUNNY_CND_HOSTNAME || true
)"
export NEXT_PUBLIC_ARTICLE_INLINE_IMAGE_UPLOAD_TOKEN="$(
  pick NEXT_PUBLIC_ARTICLE_INLINE_IMAGE_UPLOAD_TOKEN ARTICLE_INLINE_IMAGE_UPLOAD_TOKEN || true
)"
export NEXT_PUBLIC_CAREER_THUMB_UPLOAD_TOKEN="$(
  pick NEXT_PUBLIC_CAREER_THUMB_UPLOAD_TOKEN ARTICLE_INLINE_IMAGE_UPLOAD_TOKEN || true
)"

missing=()
[ -z "$CLOUDFLARE_API_TOKEN" ] && missing+=("CLOUDFLARE_API_TOKEN (token deploy Workers — không dùng CLOUDFLARE_IMAGES_API_TOKEN)")
[ -z "$CLOUDFLARE_ACCOUNT_ID" ] && missing+=("CLOUDFLARE_ACCOUNT_ID")
[ -z "$CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE" ] && missing+=("DATABASE_URL hoặc CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE")
[ -z "$NEXT_PUBLIC_SUPABASE_URL" ] && missing+=("NEXT_PUBLIC_SUPABASE_URL")
[ -z "$NEXT_PUBLIC_SUPABASE_ANON_KEY" ] && missing+=("NEXT_PUBLIC_SUPABASE_ANON_KEY")
[ -z "$NEXT_PUBLIC_CF_IMAGES_ACCOUNT_HASH" ] && missing+=("NEXT_PUBLIC_CF_IMAGES_ACCOUNT_HASH")
[ -z "$NEXT_PUBLIC_BUNNY_LIBRARY_ID" ] && missing+=("NEXT_PUBLIC_BUNNY_LIBRARY_ID hoặc BUNNY_LIBRARY_ID")
[ -z "$NEXT_PUBLIC_BUNNY_CDN_HOSTNAME" ] && missing+=("NEXT_PUBLIC_BUNNY_CDN_HOSTNAME hoặc BUNNY_CDN_HOSTNAME")
[ -z "$NEXT_PUBLIC_ARTICLE_INLINE_IMAGE_UPLOAD_TOKEN" ] && missing+=("NEXT_PUBLIC_ARTICLE_INLINE_IMAGE_UPLOAD_TOKEN hoặc ARTICLE_INLINE_IMAGE_UPLOAD_TOKEN")

if [ "${#missing[@]}" -gt 0 ]; then
  echo "::error title=Thiếu GitHub secrets::Thêm các Repository secrets sau (Settings → Secrets → Actions):"
  printf '  - %s\n' "${missing[@]}"
  echo ""
  echo "Quan trọng: CLOUDFLARE_API_TOKEN là token deploy Workers (Cloudflare Dashboard → My Profile → API Tokens → Edit Cloudflare Workers)."
  echo "Không dùng CLOUDFLARE_IMAGES_API_TOKEN thay thế."
  exit 1
fi

if [ -n "${GITHUB_ENV:-}" ]; then
  {
    echo "CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN"
    echo "CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID"
    echo "CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE=$CLOUDFLARE_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE"
    echo "WRANGLER_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE=$WRANGLER_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE"
    echo "NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL"
    echo "NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL"
    echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY"
    echo "NEXT_PUBLIC_CF_IMAGES_ACCOUNT_HASH=$NEXT_PUBLIC_CF_IMAGES_ACCOUNT_HASH"
    echo "NEXT_PUBLIC_BUNNY_LIBRARY_ID=$NEXT_PUBLIC_BUNNY_LIBRARY_ID"
    echo "NEXT_PUBLIC_BUNNY_CDN_HOSTNAME=$NEXT_PUBLIC_BUNNY_CDN_HOSTNAME"
    echo "NEXT_PUBLIC_ARTICLE_INLINE_IMAGE_UPLOAD_TOKEN=$NEXT_PUBLIC_ARTICLE_INLINE_IMAGE_UPLOAD_TOKEN"
    echo "NEXT_PUBLIC_CAREER_THUMB_UPLOAD_TOKEN=$NEXT_PUBLIC_CAREER_THUMB_UPLOAD_TOKEN"
  } >> "$GITHUB_ENV"
fi

echo "[ci] Deploy env OK (CLOUDFLARE_API_TOKEN và NEXT_PUBLIC_* đã resolve)."
